//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 12/22/2023 9:22:09 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace phoneBill.Models
{
    public partial class Member {

        public Member()
        {
            OnCreated();
        }

        public virtual int ID { get; set; }

        [Required]
        [Display(Name = "กรุณาชื่อผู้ใช้งานเบอร์โทรศัพท์")]
        [StringLength(100)]
        public virtual string Name { get; set; }

        [Required]
        [Display(Name = "กรุณากรอกเบอร์โทรศัพท์")]
        [StringLength(10)]
        public virtual string Telephone { get; set; }

        [Required]
        [Display(Name = "กรุณากรอกรหัสพนักงานผู้รับผิดชอบ")]
        [StringLength(10)]
        public virtual string EmpID { get; set; }

        [Required]
        [Display(Name = "กรุณาเลือกโปรโมชั่น")]
        public virtual string PromotionID { get; set; }

        public virtual bool? DeleteStatus { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
