//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 12/22/2023 9:22:09 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace phoneBill.Models
{
    public partial class Promotion {

        public Promotion()
        {
            OnCreated();
        }

        public virtual int ID { get; set; }

        /// <summary>
        /// โปรดมชั่นค่าโทรศัพท์
        /// </summary>
        public virtual string Promotion1 { get; set; }

        public virtual string Camp { get; set; }

        public virtual int? DeleteStatus { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
